http:
  addr: 0.0.0.0:8083
  default_secretKey: "welcome. winn.zhai"

log:
  level:  "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backet: 7

database:
  hostname:  xxxx
  dbtype: mysql
  port: 3306
  username: xxx
  password:  xxx
  base: send_alert
  ping_attempts: 3
